const express = require('express');
const router = express.Router();
const usuarioController = require('../controladores/usuarioControlador');
router.get('',usuarioController.obtenerusuarios);
router.get('/:id', usuarioController.obtenerusuariosporid);
router.post('/', usuarioController.crearusuarios);
router.put('/:id', usuarioController.actualizarusuarios);
router.delete('/', usuarioController.eliminarusuarios);
router.post('/login', usuarioController.login);
module.exports = router;
